name: "Validate ali Wrapper"
on: 
 workflow_dispatch:
jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          java-version: '17'
          distribution: 'adopt'  
      - name: buildinng
        run: |
          ls -ltr
          cd example-projects/spring-boot/
          ./gradlew build
          ls -ltr build/reports/jgiven/test/html/index.html
          cat build/reports/jgiven/test/html/index.html
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'example-projects/spring-boot/build/reports/jgiven/test/html/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
